- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes
      become_user: root

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes
      become_user: root

    - name: Stop existing containers
      shell: "docker stop $(docker ps -q) || true"
      ignore_errors: yes

    - name: Delete all containers
      shell: "docker rm $(docker ps -a -q) || true"

    - name: Pull Docker image
      command: "docker pull advit2012/banking6aug:1.0"
      register: pull_result

    - name: Remove old image if pull was successful
      shell: "docker rmi $(docker images -q advit2012/banking6aug:1.0 | tail -n +2)"
      when: pull_result.changed

    - name: Deploy Docker Container
      shell: "docker run -itd -p 8084:8081 advit2012/banking6aug:1.0"
